"""Generate matching C/SystemVerilog constants from the protocol definition."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
spec = json.loads((ROOT / "protocol/memory_map.json").read_text())
offsets = spec["offsets"]
regions = [(offsets["BUFFER0"], spec["frame_bytes"]),
           (offsets["BUFFER1"], spec["frame_bytes"]),
           (offsets["AUDIO_RING"], spec["audio_capacity"] * 4),
           (offsets["CART_SOURCE"], 8 + spec["cart_source_capacity"]),
           (offsets["CART_DATA"], spec["cart_capacity"])]
assert spec["pixel_bytes"] == 4
assert spec["frame_bytes"] == spec["width"] * spec["height"] * spec["pixel_bytes"]
assert spec["audio_capacity"] & (spec["audio_capacity"] - 1) == 0
controls = [(offsets[name], spec["keyboard_bytes"] if name == "KEYBOARD_BITS" else 8)
            for name in offsets if name not in {"BUFFER0", "BUFFER1", "AUDIO_RING", "CART_SOURCE", "CART_DATA"}]
assert spec["keyboard_bytes"] == 64
assert max(start + size for start, size in controls) <= regions[0][0]
for i, (start, size) in enumerate(controls):
    assert start % 8 == 0
    for other, other_size in controls[i + 1:]:
        assert start + size <= other or other + other_size <= start
for i, (start, size) in enumerate(regions):
    assert start % 8 == 0
    assert start + size <= spec["region_bytes"]
    for other, other_size in regions[i + 1:]:
        assert start + size <= other or other + other_size <= start
values = {"MAGIC": spec["magic"], "PHYSICAL_BASE": spec["physical_base"],
          "STATS_MAGIC": spec["statistics_magic"],
          "REGION_BYTES": spec["region_bytes"], "WIDTH": spec["width"],
          "HEIGHT": spec["height"], "PIXEL_BYTES": spec["pixel_bytes"], "FRAME_BYTES": spec["frame_bytes"],
          "AUDIO_CAPACITY": spec["audio_capacity"], "CART_CAPACITY": spec["cart_capacity"],
          "CART_SOURCE_CAPACITY": spec["cart_source_capacity"], "CART_SOURCE_MAGIC": spec["cart_source_magic"],
          "INPUT_EXTENSION_MAGIC": spec["input_extension_magic"],
          "KEYBOARD_BYTES": spec["keyboard_bytes"]}
values.update({name + "_OFFSET": value for name, value in offsets.items()})
c = "/* Generated by tools/generate_protocol.py; do not edit. */\n#ifndef TIC80_MISTER_MEMORY_MAP_H\n#define TIC80_MISTER_MEMORY_MAP_H\n"
sv = "// Generated by tools/generate_protocol.py; do not edit.\n"
for name, value in values.items():
    c += f"#define TM_{name} 0x{value:08X}u\n"
    sv += f"localparam logic [31:0] TM_{name} = 32'h{value:08X};\n"
c += "#endif\n"
for name, content in [("include/tic80_mister/memory_map.h", c), ("fpga/rtl/memory_map.svh", sv)]:
    path = ROOT / name
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"Stale generated constants: {name}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
