"""Equivalent explicit SFX calls in all runtimes; Wren stereo-list overloads."""
import argparse,json
from pathlib import Path
from generate_api_bank_cases import LANGUAGES,expr,leb

PLAN=[(0,(0,60,8,2,15,3)),(2,(1,50,10,0,5,-2)),(5,(-1,0,0,2,0,0)),
      (7,(0,31,6,1,7,1)),(9,(-1,0,0,0,0,0)),(13,(1,48,-1,3,15,0)),
      (14,(-1,0,0,1,0,0))]+[(18,(-1,0,0,c,0,0)) for c in range(4)]
def operation(args,lang):
    if lang=='forth':
        index,note,duration,channel,volume,speed=args
        return f'{index} {note%12} {note//12} {duration} {channel} {volume} {speed} SFX'
    return expr(('sfx',args),lang)
def source(lang):
    if lang=='forth':
        out=': TIC 31 PMEM\n'
        for n,args in PLAN: out+=f' DUP {n} = IF {operation(args,lang)} THEN\n'
        return out+' 1+ 31 PMEM! ;\n'
    get=expr(('pmem',(31,)),lang); put=expr(('pmem',(31,('add',('n',1)))),lang)
    if lang in ('fennel','scheme','janet'):
        start={'fennel':f'(fn _G.TIC [] (let [n {get}]\n',
               'scheme':f'(define (TIC) (let ((n {get}))\n',
               'janet':f'(import tic80)\n(defn TIC [] (def n {get})\n'}[lang]
        return start+''.join(f' (when (= n {n}) {operation(args,lang)})\n' for n,args in PLAN)+' '+put+('\n)\n' if lang=='janet' else '\n))\n')
    starts={'lua':'function TIC()\n','js':'function TIC(){\n','squirrel':'function TIC(){\n',
            'moon':'export TIC\nTIC = ->\n','yue':'global TIC = ->\n','python':'def TIC():\n',
            'ruby':'def TIC\n','miniscript':'TIC=function\n','wren':'class Game is TIC {\n construct new() {}\n TIC() {\n'}
    declaration='var ' if lang in ('js','wren') else 'local ' if lang in ('lua','squirrel') else ''
    out=starts[lang]+' '+declaration+'n='+get+('\n')
    for n,args in PLAN:
        if lang in ('js','squirrel','wren'): out+=f' if(n=={n}) {{ {operation(args,lang)} }}\n'
        elif lang in ('lua','miniscript'): out+=f' if n=={n} then\n  {operation(args,lang)}\n'+(' end\n' if lang=='lua' else ' end if\n')
        else: out+=f' if n=={n}'+(':' if lang=='python' else '')+f'\n  {operation(args,lang)}\n'+(' end\n' if lang=='ruby' else '')
    out+=' '+put+'\n'
    return out+{'lua':'end\n','ruby':'end\n','miniscript':'end function\n','js':'}\n','squirrel':'}\n','wren':' }\n}\n'}.get(lang,'')
def wasm():
    string=lambda s:leb(len(s))+s.encode(); vector=lambda xs:leb(len(xs))+b''.join(xs)
    section=lambda n,b:bytes([n])+leb(len(b))+b
    types=[([0x7f]*8,[]),([0x7f,0x7e],[0x7f]),([],[])]
    module=b'\0asm\x01\0\0\0'+section(1,vector([b'\x60'+bytes([len(p)])+bytes(p)+bytes([len(r)])+bytes(r) for p,r in types]))
    module+=section(2,vector([string('env')+string(n)+b'\0'+leb(i) for i,n in enumerate(('sfx','pmem'))]))
    module+=section(3,b'\x01\x02')+section(5,b'\x01\x00\x04')+section(7,vector([string('TIC')+b'\0\x02']))
    integer=lambda n:b'\x41'+leb(n,True)
    body=b'\x01\x01\x7f'+integer(31)+b'\x42\x7f\x10\x01\x21\0'
    for n,args in PLAN:
        index,note,duration,channel,volume,speed=args
        body+=b'\x20\0'+integer(n)+b'\x46\x04\x40'
        body+=b''.join(integer(a) for a in (index,note%12,note//12,duration,channel,volume,volume,speed))+b'\x10\0\x0b'
    body+=integer(31)+b'\x20\0'+integer(1)+b'\x6a\xad\x10\x01\x1a\x0b'
    return module+section(10,vector([leb(len(body))+body]))
def stereo(variant):
    args=[(0,'0,48,8,2,[0,15]'+(',3' if variant==2 else '')),
          (6,'1,50,10,0,[15,0]'+(',-1' if variant==2 else '')),
          (12,'-1,0,0,2,[0,0]'+(',0' if variant==2 else '')),
          (14,'-1,0,0,0,[0,0]'+(',0' if variant==2 else ''))]
    return 'class Game is TIC {\n construct new() {}\n TIC() {\n var n=TIC.pmem(31)\n'+''.join(f' if(n=={n}) {{ TIC.sfx({a}) }}\n' for n,a in args)+' TIC.pmem(31,n+1)\n }\n}\n'
def main():
    parser=argparse.ArgumentParser(description=__doc__); parser.add_argument('--output',type=Path,required=True); args=parser.parse_args()
    binary=wasm(); out='/* Generated by tools/generate_sfx_cases.py. */\nstatic const unsigned char sfx_wasm[] = {'+','.join(map(str,binary))+'};\n'
    out+='static const struct { const char *language; unsigned variant; const char *source; const unsigned char *binary; unsigned size; } sfx_cases[] = {\n'
    for lang in LANGUAGES:
        out+=f'{{"{lang}",0,'+( '"// script: wasm\\n",sfx_wasm,sizeof sfx_wasm' if lang=='wasm' else json.dumps(source(lang))+',NULL,0')+'},\n'
    for variant in (1,2): out+=f'{{"wren",{variant},'+json.dumps(stereo(variant))+',NULL,0},\n'
    out+='};\n'; args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text(out)
if __name__=='__main__': main()
