"""MiniScript SFX defaults and shared Lua-family stereo volume contracts."""
import argparse
import json
from pathlib import Path

CALLS = [
    ('zero', '0'), ('one', '1'), ('last', '63'),
    ('zero-duration', '0,null,6'), ('last-duration', '63,null,6'),
    ('zero-note', '0,48'), ('zero-speed', '0,null,-1,2,15,0'),
    ('zero-explicit', '0,60,8,1,5,3'),
    ('zero-stereo', '0,null,7,3,[0,15]'), ('stop', '-1'),
]

def source(language, name, arguments):
    prefix = 'tic80.' if language == 'miniscript' else ''
    arguments = arguments if language == 'miniscript' else arguments.replace('null', 'nil').replace('[0,15]', '{0,15}')
    if language == 'fennel':
        args = arguments.replace('{0,15}', 'STEREO').split(',')
        args = ' '.join(args).replace('STEREO', '[0 15]')
        out = '(fn _G.TIC [] (let [n (pmem 31)]\n'
        if name == 'stop':
            out += ' (when (= n 0) (sfx 0))\n'
        out += f' (when (= n {2 if name == "stop" else 0}) (sfx {args}))\n'
        out += ' (when (= n 12)\n' + ''.join(f'  (sfx -1 0 0 {c} 0 0)\n' for c in range(4)) + ' )\n'
        return out + ' (pmem 31 (+ n 1))))\n'
    if language in ('moon', 'yue'):
        out = 'export TIC\nTIC = ->\n' if language == 'moon' else 'global TIC = ->\n'
        out += ' n=pmem(31)\n'
        if name == 'stop':
            out += ' if n==0\n  sfx(0)\n'
        out += f' if n=={2 if name == "stop" else 0}\n  sfx({arguments})\n'
        out += ' if n==12\n' + ''.join(f'  sfx(-1,0,0,{c},0,0)\n' for c in range(4))
        return out + ' pmem(31,n+1)\n'
    start = 'TIC=function\n' if language == 'miniscript' else 'function TIC()\n'
    end = 'end function\n' if language == 'miniscript' else 'end\n'
    close = 'end if' if language == 'miniscript' else 'end'
    out = start + (' n=' if language == 'miniscript' else ' local n=') + prefix + 'pmem(31)\n'
    if name == 'stop':
        out += f' if n==0 then\n  {prefix}sfx(0)\n {close}\n'
        frame = 2
    else:
        frame = 0
    out += f' if n=={frame} then\n  {prefix}sfx({arguments})\n {close}\n'
    out += f' if n==12 then\n'
    for channel in range(4):
        out += f'  {prefix}sfx(-1,0,0,{channel},0,0)\n'
    return out + f' {close}\n {prefix}pmem(31,n+1)\n' + end

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    out = '/* Generated by tools/generate_sfx_defaults_cases.py; expectations live in the C fixture. */\n'
    out += 'static const struct { const char *language, *name, *source; unsigned scenario; } defaults_cases[] = {\n'
    for language in ('lua', 'moon', 'yue', 'fennel', 'miniscript'):
        for scenario, (name, arguments) in enumerate(CALLS):
            out += '{' + ','.join((json.dumps(language), json.dumps(name), json.dumps(source(language, name, arguments)), str(scenario))) + '},\n'
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(out + '};\n')

if __name__ == '__main__':
    main()
